name: Heroku Dyno Switcher V2
on:
  schedule:
  - cron: "0 0 1,23 * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'
      - name: Installing heroku3
        run: pip install -r requirements.txt
      - name: Switching the Dynos
        run: python3 script_noloop.py
        env:
          A_APPNAME: ${{ secrets.A_APPNAME }}
          A_APIKEY: ${{ secrets.A_APIKEY }}
          B_APPNAME: ${{ secrets.B_APPNAME }}
          B_APIKEY: ${{ secrets.B_APIKEY }}
          PROCESSTYPE: ${{ secrets.PROCESSTYPE }}
          CA_APPNAME: ${{ secrets.CA_APPNAME }}
          CB_APPNAME: ${{ secrets.CB_APPNAME }}
          C_APIKEY: ${{ secrets.C_APIKEY }}
